# Generated by Django 5.2 for myCamino.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("siteapp", "0002_downloadevent")]

    operations = [
        migrations.CreateModel(
            name="ApplicationNews",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=240)),
                ("summary", models.TextField(max_length=4000)),
                ("kind", models.CharField(choices=[("news", "News"), ("update", "Update")], default="news", max_length=12)),
                ("app_version", models.CharField(blank=True, max_length=40)),
                ("link", models.URLField(blank=True)),
                ("published_at", models.DateTimeField()),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "application news",
                "ordering": ("-published_at", "-created_at"),
            },
        )
    ]
